services:
  index-postgresql:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: index-postgresql
    image: index-postgresql-timescaledb:latest
    restart: unless-stopped
    command: postgres -c shared_preload_libraries=timescaledb
    environment:
      POSTGRES_DB: future_index
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - D:/futureindexdb:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d future_index" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  index-clickhouse:
    build:
      context: .
      dockerfile: Dockerfile.clickhouse
    container_name: index-clickhouse
    image: index-clickhouse:latest
    restart: unless-stopped
    ports:
      - "8123:8123" # HTTP interface
      - "9000:9000" # Native interface
    volumes:
      - D:/clickhousedb:/var/lib/clickhouse
      - ./clickhouse-config/users.xml:/etc/clickhouse-server/users.d/users.xml
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: [ "CMD-SHELL", "clickhouse-client --query 'SELECT 1'" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
