[project]
name = "scid-parser"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "asyncpg>=0.31.0",
    "clickhouse-driver>=0.2.10",
    "h5py>=3.15.1",
    "numpy>=2.3.5",
    "pandas>=2.3.3",
]
